# Generated by Django 5.0.6 on 2024-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_day_left_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inquiry',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
