# Generated by Django 5.0.6 on 2024-06-10 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_inquiry_post_scrap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrap_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='post',
            name='scrap',
        ),
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='scraped', to=settings.AUTH_USER_MODEL),
        ),
    ]
