# Generated by Django 5.0.6 on 2024-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
