# Generated by Django 5.0.6 on 2024-06-12 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_applicated_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(blank=True, default=None, related_name='scraped', to=settings.AUTH_USER_MODEL),
        ),
    ]
