# Generated by Django 5.0.6 on 2024-06-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_post_content_remove_post_is_attending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
