# Generated by Django 5.0.6 on 2024-06-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_applicated_application_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='inquiry',
        ),
    ]
