# Generated by Django 5.0.6 on 2024-06-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_post_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='building',
        ),
    ]
