# Generated by Django 5.0.6 on 2024-06-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_post_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recruitment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
