# Generated by Django 5.0.6 on 2024-06-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_post_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='answer_file/'),
        ),
    ]
