# Generated by Django 5.0.6 on 2024-06-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_application_is_accepted_alter_answer_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicated',
        ),
    ]
