# Generated by Django 5.0.6 on 2024-06-23 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_applicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.post'),
        ),
    ]
