# Generated by Django 5.0.6 on 2024-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_application_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='file',
        ),
        migrations.AddField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='application_file/'),
        ),
    ]
