# Generated by Django 5.0.6 on 2024-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_answer_file_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TextField(),
        ),
    ]
