# Generated by Django 5.0.6 on 2024-06-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
    ]
