# Generated by Django 5.0.6 on 2024-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
