# Generated by Django 5.0.6 on 2024-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certification_staff',
            field=models.FileField(null=True, upload_to='staff_certification/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certification_student',
            field=models.FileField(null=True, upload_to='student_certification/'),
        ),
    ]
